# General
permalink   : /:categories/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

# Site settings
title: Fintech to Go
description: "The fastest way to keep up with Fintech news."
keywords: fintech, news, media
email: tripathi@vesthq.com
url: http://www.fintechtogo.com
repository: https://github.com/vesthq/fintechtogo
google_analytics: UA-79162503-1
