# General
permalink   : /:categories/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

# Site settings
title: Vest
description: "A fintech lab."
keywords: fintech, news, media
email: tripathi@vesthq.com
url: http://www.vesthq.com
repository: https://github.com/vesthq/vesthq
google_analytics: UA-72011621-1

plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 10 versions